apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
  namespace : dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: akspvc.azurecr.io/bprasanna881/spring-aks:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        volumeMounts:
            - name: foo
              mountPath: "/etc/foo"
              readOnly: true
      volumes:
      - name: foo 
        secret:
          secretName: mssql-secret      
---
# service type loadbalancer
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
  namespace : dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app
---
# secrets
apiVersion: v1
kind: Secret
metadata:
  name:  mssql-secret
data:
   db-connection-string-secret: U2VydmVyPW1zc3FsLXNlcnZpY2U7RGF0YWJhc2U9UHJvZGN1dHNEQjtVc2VyPVNBO1Bhc3N3b3JkPUBBYTEyMzQ1Njs=
type: Opaque


