apiVersion : apps/v1
kind: Deployment
metadata:
  name: springyaml
spec:
  replicas: 5
  selector:
    matchLabels:
      app: springyaml
  template:
    metadata:
      labels:
        app: springyaml
    spec:
      containers:
        - name: springyaml
          image: akspvc.azurecr.io/springyaml
          ports:
          - containerPort: 80
          
