apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-disk-claim-1
  labels:
    app: springboot-app
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 20G
